# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET https://localhost:32774/api/ping

###

GET https://localhost:32774/api/jobs/running

###

GET https://localhost:32774/api/short

###

GET https://localhost:32774/api/short/stop

###

GET https://localhost:32774/api/medium

###

GET https://localhost:32774/api/medium/stop

###

GET https://localhost:32774/api/long

###

GET https://localhost:32774/api/long/stop
